//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Degadis.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Degadis.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        internal static string kAgregar {
            get {
                return ResourceManager.GetString("kAgregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parámetros Atmosféricos.
        /// </summary>
        internal static string kAtmPar {
            get {
                return ResourceManager.GetString("kAtmPar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar caso.
        /// </summary>
        internal static string KBuscCaso {
            get {
                return ResourceManager.GetString("KBuscCaso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Constante de capacidad calorífica del contaminante [J/kg/K].
        /// </summary>
        internal static string kCapCal {
            get {
                return ResourceManager.GetString("kCapCal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coeficiente de transferencia de calor [J/m^2/s/K].
        /// </summary>
        internal static string kCoefTransCal {
            get {
                return ResourceManager.GetString("kCoefTransCal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Concentración de contaminantes [kg/m3].
        /// </summary>
        internal static string kConcCon {
            get {
                return ResourceManager.GetString("kConcCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correlación Degadis.
        /// </summary>
        internal static string kCorrDegadis {
            get {
                return ResourceManager.GetString("kCorrDegadis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correlación LLNL.
        /// </summary>
        internal static string kCorrLLNL {
            get {
                return ResourceManager.GetString("kCorrLLNL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear nuevo caso.
        /// </summary>
        internal static string kCrearCaso {
            get {
                return ResourceManager.GetString("kCrearCaso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Curva de densidad.
        /// </summary>
        internal static string kCurva {
            get {
                return ResourceManager.GetString("kCurva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por defecto.
        /// </summary>
        internal static string kDefault {
            get {
                return ResourceManager.GetString("kDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo medio estimado DELTAY [s].
        /// </summary>
        internal static string kDELTAY {
            get {
                return ResourceManager.GetString("kDELTAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Densidad de la mezcla [kg/m3].
        /// </summary>
        internal static string kDensCon {
            get {
                return ResourceManager.GetString("kDensCon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Densidad de liberación de contaminantes [kg/m3].
        /// </summary>
        internal static string kDensGas {
            get {
                return ResourceManager.GetString("kDensGas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        internal static string kDescrip {
            get {
                return ResourceManager.GetString("kDescrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción de la versión.
        /// </summary>
        internal static string kDescVer {
            get {
                return ResourceManager.GetString("kDescVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle del Matrial.
        /// </summary>
        internal static string kDetalle {
            get {
                return ResourceManager.GetString("kDetalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese el diámetro de la fuente [m].
        /// </summary>
        internal static string kDiamFuente {
            get {
                return ResourceManager.GetString("kDiamFuente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diluido.
        /// </summary>
        internal static string kDiluido {
            get {
                return ResourceManager.GetString("kDiluido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Duración de la fuente [s].
        /// </summary>
        internal static string kDuracionFuente {
            get {
                return ResourceManager.GetString("kDuracionFuente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Caso.
        /// </summary>
        internal static string kEditCaso {
            get {
                return ResourceManager.GetString("kEditCaso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese la elevación de la fuente [m].
        /// </summary>
        internal static string kElevFuente {
            get {
                return ResourceManager.GetString("kElevFuente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elevación para salida de contorno (receptor) [m].
        /// </summary>
        internal static string kElevRec {
            get {
                return ResourceManager.GetString("kElevRec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Se puede considerar esta liberación: en estado estacionario o transitoria?.
        /// </summary>
        internal static string kEoT {
            get {
                return ResourceManager.GetString("kEoT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Especificar propiedades contaminante.
        /// </summary>
        internal static string kEspCont {
            get {
                return ResourceManager.GetString("kEspCont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estabilidad Pasquill.
        /// </summary>
        internal static string kEstabilidad {
            get {
                return ResourceManager.GetString("kEstabilidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estacionaria.
        /// </summary>
        internal static string kEstacionaria {
            get {
                return ResourceManager.GetString("kEstacionaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Liberación de estado estacionario.
        /// </summary>
        internal static string kEstEstacionario {
            get {
                return ResourceManager.GetString("kEstEstacionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Liberación de estado transitorio.
        /// </summary>
        internal static string kEstTrans {
            get {
                return ResourceManager.GetString("kEstTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formula gas.
        /// </summary>
        internal static string kFormula {
            get {
                return ResourceManager.GetString("kFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fracción de masa.
        /// </summary>
        internal static string kFracMas {
            get {
                return ResourceManager.GetString("kFracMas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fracción molar contaminante.
        /// </summary>
        internal static string kFracMol {
            get {
                return ResourceManager.GetString("kFracMol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fracción molar más baja de interés.
        /// </summary>
        internal static string kFracMolBaja {
            get {
                return ResourceManager.GetString("kFracMolBaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Humedad ambiente absoluta [kg agua/kg aire seco].
        /// </summary>
        internal static string kHumAbs {
            get {
                return ResourceManager.GetString("kHumAbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Humedad ambiente relativa [%].
        /// </summary>
        internal static string kHumRel {
            get {
                return ResourceManager.GetString("kHumRel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Es este un derrame de &quot;isoterma&quot;?.
        /// </summary>
        internal static string kIsoterma {
            get {
                return ResourceManager.GetString("kIsoterma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tasa de liberación de contaminantes [kg/s].
        /// </summary>
        internal static string kLibCont {
            get {
                return ResourceManager.GetString("kLibCont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista de contaminantes disponibles.
        /// </summary>
        internal static string kListGas {
            get {
                return ResourceManager.GetString("kListGas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Límite inferior de preocupación como fracción molar
        ///(LLC).
        /// </summary>
        internal static string kLLC {
            get {
                return ResourceManager.GetString("kLLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese la fracción de masa del contaminante de origen.
        /// </summary>
        internal static string kMasaCont {
            get {
                return ResourceManager.GetString("kMasaCont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Masa inicial de contaminante puro sobre la fuente [kg].
        /// </summary>
        internal static string KMasaIni {
            get {
                return ResourceManager.GetString("KMasaIni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modelo Degadis.
        /// </summary>
        internal static string kMDeg {
            get {
                return ResourceManager.GetString("kMDeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modelo Jet/Plume.
        /// </summary>
        internal static string kMJet {
            get {
                return ResourceManager.GetString("kMJet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Longitud de Monin-Obukhov [m].
        /// </summary>
        internal static string kMonin {
            get {
                return ResourceManager.GetString("kMonin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        internal static string kNo {
            get {
                return ResourceManager.GetString("kNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de archivo.
        /// </summary>
        internal static string kNomArch {
            get {
                return ResourceManager.GetString("kNomArch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo Gas.
        /// </summary>
        internal static string kNuevoGas {
            get {
                return ResourceManager.GetString("kNuevoGas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Peso molecular del contaminante [kg/kmol].
        /// </summary>
        internal static string kPesoMol {
            get {
                return ResourceManager.GetString("kPesoMol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Se libera el contaminante: puro o diluido con aire?.
        /// </summary>
        internal static string kPoD {
            get {
                return ResourceManager.GetString("kPoD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Potencia de capacidad calorífica contaminante.
        /// </summary>
        internal static string kPoteCalGas {
            get {
                return ResourceManager.GetString("kPoteCalGas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Presión ambiente [atm].
        /// </summary>
        internal static string kPresAmb {
            get {
                return ResourceManager.GetString("kPresAmb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puro.
        /// </summary>
        internal static string kPuro {
            get {
                return ResourceManager.GetString("kPuro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese el radio de la fuente [m].
        /// </summary>
        internal static string kRadFuente {
            get {
                return ResourceManager.GetString("kRadFuente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Radio de origen [m].
        /// </summary>
        internal static string kRadOrig {
            get {
                return ResourceManager.GetString("kRadOrig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rugosidad superficial, zr [m].
        /// </summary>
        internal static string kRugosidad {
            get {
                return ResourceManager.GetString("kRugosidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar
        ///carpeta.
        /// </summary>
        internal static string kSelCarp {
            get {
                return ResourceManager.GetString("kSelCarp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar.
        /// </summary>
        internal static string kSet {
            get {
                return ResourceManager.GetString("kSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si.
        /// </summary>
        internal static string kSi {
            get {
                return ResourceManager.GetString("kSi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Siguiente.
        /// </summary>
        internal static string kSiguiente {
            get {
                return ResourceManager.GetString("kSiguiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sobreescribir caso.
        /// </summary>
        internal static string kSobreCaso {
            get {
                return ResourceManager.GetString("kSobreCaso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese la tasa de liberación [kg de contaminante/s].
        /// </summary>
        internal static string kTasaLib {
            get {
                return ResourceManager.GetString("kTasaLib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Temperatura del aire [K].
        /// </summary>
        internal static string kTempAire {
            get {
                return ResourceManager.GetString("kTempAire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Temperatura de liberación de contaminantes [K].
        /// </summary>
        internal static string kTempCalGas {
            get {
                return ResourceManager.GetString("kTempCalGas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese la temperatura de la fuente [K].
        /// </summary>
        internal static string kTempFuente {
            get {
                return ResourceManager.GetString("kTempFuente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Temperatura del suelo [K].
        /// </summary>
        internal static string kTempSuelo {
            get {
                return ResourceManager.GetString("kTempSuelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo [s].
        /// </summary>
        internal static string kTiempo {
            get {
                return ResourceManager.GetString("kTiempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Titulo.
        /// </summary>
        internal static string kTitulo {
            get {
                return ResourceManager.GetString("kTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Debe incluirse la transferencia de calor en los cálculos?.
        /// </summary>
        internal static string kTransfCalor {
            get {
                return ResourceManager.GetString("kTransfCalor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Se incluirá la transferencia de agua en los cálculos?.
        /// </summary>
        internal static string kTransfereAgua {
            get {
                return ResourceManager.GetString("kTransfereAgua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transitoria.
        /// </summary>
        internal static string kTransitoria {
            get {
                return ResourceManager.GetString("kTransitoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Velocidad del viento, u0 [m/s].
        /// </summary>
        internal static string kU0 {
            get {
                return ResourceManager.GetString("kU0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Límite superior de preocupación como fracción molar
        ///(ULC).
        /// </summary>
        internal static string kULC {
            get {
                return ResourceManager.GetString("kULC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor particular.
        /// </summary>
        internal static string kValPar {
            get {
                return ResourceManager.GetString("kValPar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Altura de medición del viento, z0 [m].
        /// </summary>
        internal static string kZ0 {
            get {
                return ResourceManager.GetString("kZ0", resourceCulture);
            }
        }
    }
}
